<<<<<<< HEAD
name: my_new_one
=======
name: my_app
>>>>>>> 4683582288b2d8b6b9983fd584d1049e26e105f1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
<<<<<<< HEAD
  sdk: ">=3.0.0 <4.0.0"
=======
  sdk: ^3.7.2
>>>>>>> 4683582288b2d8b6b9983fd584d1049e26e105f1

dependencies:
  flutter:
    sdk: flutter
<<<<<<< HEAD
  firebase_core: ^2.15.1
  firebase_auth: ^4.4.0
  google_sign_in: ^6.1.0
  flutter_secure_storage: ^8.0.0
  flutter_dotenv: ^5.1.0

  cupertino_icons: ^1.0.8
=======
  cupertino_icons: ^1.0.8
  firebase_core: ^2.25.4
  firebase_auth: ^4.14.0
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

>>>>>>> 4683582288b2d8b6b9983fd584d1049e26e105f1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
<<<<<<< HEAD
=======

>>>>>>> 4683582288b2d8b6b9983fd584d1049e26e105f1
